#!/bin/sh

set -e
name=$1

test $name || {
  echo "Usage: $0 name-of-unit"
  exit
}

mkdir $name
touch $name/deps
touch $name/readme.md
touch $name/install.sh
touch $name/installed.sh

# Open all the files in sublime
which -s subl && subl $name/*
