#!/bin/sh

set -e
name=$1

test $name || {
  echo "Usage: $0 name-of-unit"
  exit
}

mkdir $name
touch $name/deps
touch $name/readme.md
touch $name/install.sh
touch $name/installed.sh

which -s subl && {
  subl $name/readme.md
  subl $name/deps
  subl $name/install.sh
  subl $name/installed.sh
}
