#!/bin/sh

set -e # Exit if any command fails

# If multiple args given run this script once for each arg
test $2 && {
  for arg in $@
    do $0 $arg
  done
  exit
}

# ---

unit_name=$1
deps_file="$unit_name/deps"
guard_file="$unit_name/installed.sh"

# Skip if this unit or any deps are blacklisted
test -f _blacklist && {
  (grep -v '^#' _blacklist | grep -x -q "^$unit_name\$" -) && {
    echo "-* skipping blacklisted $unit_name"
    exit
  }
  test -f $deps_file && {
    for dep_name in `<$deps_file` ; do
      (grep -v '^#' _blacklist | grep -x -q $dep_name -) && {
        echo "-* skipping $unit_name due to blacklisted dep $dep_name"
        exit
      }
    done
  }
}

# Exit if there's a guard file and the guard detects an install
test -f $guard_file && sh $guard_file && {
  echo "-* $unit_name installed"
  exit
}

# Otherwise install deps
test -f $deps_file && $0 `cat $deps_file`

# Then install unit
echo "-* installing $unit_name"
sh "$unit_name/install.sh"

# Exit error if the guard still doesn't pass after install
test -f $guard_file && sh $guard_file || {
  echo "-* $unit_name install script finished but installed test failed"
  exit 1
}
