source 'https://rubygems.org'

# utility gems
gem 'debugger'
gem 'pry'
gem 'seeing_is_believing'
gem 'rspec', ' ~> 2.99'
gem 'better_errors'
gem 'binding_of_caller'
gem 'byebug'
gem 'pry-byebug'

# Phase 1
gem 'nokogiri'
gem 'sqlite3'
gem 'faker'

# Phase 2
gem 'bcrypt-ruby'
gem 'carrierwave'
gem 'factory_girl'
gem 'oauth'
gem 'oauth2'
gem 'pg'
gem 'redis'
gem 'sidekiq'
gem 'sinatra'
gem 'sinatra-contrib'
gem 'twitter'
gem 'thin'
gem 'shotgun'

# Phase 3
gem 'capybara'
gem 'dalli'
gem 'rails', '= 4.1.3'


